language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install pytest-cov
  - pip install coveralls

install:
  - pip install -r requirements.txt

script:
  - py.test --cov=dcard tests/

after_success:
  - coveralls
